### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by g12n** [ubergesundheit/ma-tiles#3]
The build failes due to changed naming

Building renderer...
Step 0 : FROM dockerfile/nodejs
Pulling repository docker.io/dockerfile/nodejs
Service 'renderer' failed to build: Error: image dockerfile/nodejs:latest not found

**Comment by ubergesundheit** [comment]
Can you try with `FROM node:0.10`?
If this works, can you create a pull request? Thanks!

**Comment by ubergesundheit** [comment]
In commit 8e67dcda8f60efeaee54d220907e6bccafcf89ed I switched to `dockerfile/node` for specific dependencies I don't know for now.. 
I will investigate this later..

**Comment by g12n** [comment]
Works with `FROM node:0.10`
have to clean up some mess before in can make a pull request.

**Comment by g12n** [comment]
Added Pull request #4
